# Generated by Django 5.2.6 on 2026-01-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_recipes',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='accounts.recipe'),
        ),
    ]
