# Generated by Django 5.2.6 on 2025-09-25 11:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recipe_likes_comment_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('user', 'title')},
        ),
    ]
