# Generated by Django 5.2.6 on 2026-02-19 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_saved_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.recipe'),
        ),
    ]
