# Generated by Django 5.2.6 on 2025-11-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_recipe_prep_time_recipe_total_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='total_time',
            new_name='prep_time',
        ),
    ]
