# Generated by Django 5.2.6 on 2025-12-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_recipes',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='accounts.recipe'),
        ),
    ]
