# Generated by Django 5.2.6 on 2025-12-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_saved_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved_recipes',
        ),
    ]
